"""
Debug & Flagging UI Panel
Toggle with F12. Captures state and generates reports for Grok review.
"""

import pygame
import json
import os
from datetime import datetime

class DebugPanel:
    def __init__(self):
        self.font = pygame.font.SysFont(None, 24)
        self.logs = []
        self.report_dir = "data/debug_logs"
        os.makedirs(self.report_dir, exist_ok=True)
    
    def draw(self, screen):
        # Semi-transparent overlay
        overlay = pygame.Surface((400, 300), pygame.SRCALPHA)
        overlay.fill((0, 0, 0, 180))
        screen.blit(overlay, (20, 20))
        
        # Title
        title = self.font.render("DEBUG & FLAGGING PANEL (F12 to close)", True, (255, 220, 100))
        screen.blit(title, (30, 30))
        
        # Instructions
        lines = [
            "Game State: [Sample - Phase 1]",
            "Rule Engine: Active",
            "Cards Loaded: Large/Medium/Small OK",
            "",
            "Press 'F' to Flag Current Issue",
            "Report saved to data/debug_logs/"
        ]
        y = 60
        for line in lines:
            text = self.font.render(line, True, (200, 200, 200))
            screen.blit(text, (30, y))
            y += 28
    
    def flag_issue(self, game_state=None):
        """Capture current context and save report."""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        report = {
            "timestamp": timestamp,
            "game_state": game_state or {"phase": "1 - Debug UI Active"},
            "note": "Auto-generated by in-game Flag button. Review with Grok."
        }
        filename = f"{self.report_dir}/flag_{timestamp}.json"
        with open(filename, "w") as f:
            json.dump(report, f, indent=2)
        print(f"Issue flagged! Report saved: {filename}")
        return filename
